<?php

/** @var \AHT\Block\Block\Template $block */
?>

<div class="template">
    <div class="container">
        <form method='POST' action="/block/index/save">
            <div class="form-group">
                <input type="hidden" name="id" value="<?php echo $block->getBlock('id');  ?>">
                <label for="title"><b>Title</b></label>
                <input type="text" class="form-control" id="title" placeholder="Title" name="title" value="<?php echo $block->getBlock('title');  ?>">
            </div>
            <br>
            <div class=" form-group">
                <label for="description"><b>Description</b></label>
                <input type="text" class="form-control" id="description" placeholder="Description" name="description" value="<?php echo $block->getBlock('description'); ?>">
            </div>
            <br>
            <button type=" submit" class="btn btn-primary" name="btn_edit">Submit</button>
        </form>
    </div>

</div>