<?php

/** @var \AHT\Bl\Block\Template $block */
?>

<div class="template">
    <div class="container">
        <form method='POST' action="save">
            <div class="form-group">
                <label for="title"><b>Title</b></label>
                <input type="text" class="form-control" id="title" placeholder="Title" name="title">
            </div>
            <br>
            <div class="form-group">
                <label for="description"><b>Description</b></label>
                <input type="text" class="form-control" id="description" placeholder="Description" name="description">
            </div>
            <br>
            <button type="submit" class="btn btn-primary" name="btn_create">Submit</button>
        </form>
    </div>

</div>
